# Generated by Django 4.2.16 on 2025-02-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_detected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detected',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='detected',
            name='longitude',
        ),
    ]
